import 'package:flutter/material.dart';
import 'package:fluttericon/elusive_icons.dart';
import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This is generated by FlutterFire CLI
import 'package:howbadami/services/auth_service.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:howbadami/pages/login_screen.dart'; // Your Login screen
import 'package:howbadami/pages/home.dart';


/// Flutter code sample for [NavigationBar].

void main() => runApp(const NavigationBarApp());

class NavigationBarApp extends StatelessWidget {
  const NavigationBarApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(theme: ThemeData(useMaterial3: true), home: const HomeScreen());
  }
}