import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart';// This is generated by FlutterFire CLI
// Your Login screen
import 'package:howbadami/pages/home.dart';
/*import 'package:howbadami/services/auth_service.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'package:howbadami/pages/login_screen.dart'; // Your Login screen*/

/// Flutter code sample for [NavigationBar].

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(const NavigationBarApp());
}

class NavigationBarApp extends StatelessWidget {
  const NavigationBarApp({super.key});


  @override
  Widget build(BuildContext context) {
    return MaterialApp(
        theme: ThemeData(useMaterial3: true), home: const HomeScreen());
  }
}

