import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:howbadami/views/widget_tree.dart';
import 'firebase_options.dart'; // This is generated by FlutterFire CLI
// Your Login screen
//import 'package:howbadami/services/auth_service.dart';// Your Login screen*/

/// Flutter code sample for [NavigationBar].

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);
  runApp(const Howbadami());
}

class Howbadami extends StatelessWidget {
  const Howbadami({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData(useMaterial3: true),
      home: const WidgetTree(),
    );
  }
}
